language: node_js

node_js:
  - "10"

cache:
  directories:
    - node_modules

script:
  - npm run build

before-deploy:
  - echo npm@containo.us ${NPM_EMAIL}
  # - >
  #   if ! [ "$BEFORE_DEPLOY_RUN" ]; then
  #     export BEFORE_DEPLOY_RUN=1;
  #     npm run deploy-storybook -- -o site;
  #   fi

deploy:
  provider: npm
  email: "matthieu.hostache@gmail.com"
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  on:
    tags: true
  # - provider: pages
  #   edge: false
  #   github_token: ${GITHUB_TOKEN}
  #   local_dir: site
  #   skip_cleanup: true
  #   on:
  #     all_branches: true
