language: node_js

node_js:
  - "stable"

cache:
  yarn: true
  directories:
    - node_modules

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

before_script:
  -  yarn global add gatsby-cli

script:
  - yarn lint
  - yarn build
  - yarn test

before_deploy:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_API_TOKEN}" >> $HOME/.npmrc 2> /dev/null
  - echo "//registry.npmjs.org/:email=\${NPM_EMAIL}" >> $HOME/.npmrc 2> /dev/null

deploy:
  - provider: script
    script: yarn website:deploy
    skip_cleanup: true
    on:
      all_branches: true
  - provider: script
    script: yarn release -y from-git
    skip_cleanup: true
    on:
      tags: true
