language: node_js

node_js:
  - "lts/*"

cache:
  directories:
    - node_modules

script:
  - npm run build

before-deploy:
  - >
    if ! [ "$BEFORE_DEPLOY_RUN" ]; then
      export BEFORE_DEPLOY_RUN=1;
      echo ${NPM_API_KEY} ${NPM_EMAIL}
      npm run deploy-storybook -- -o site;
    fi

deploy:
  # - provider: pages
  #   edge: false
  #   github_token: ${GITHUB_TOKEN}
  #   local_dir: site
  #   skip_cleanup: true
  #   on:
  #     all_branches: true
  - provider: npm
    email: 'npm@containo.us'
    api_key: '$NPM_API_KEY'
    skip_cleanup: true
    on:
      all_branches: true
